- hosts: all
  become: true
  tasks:
    - name: group add  
      group: 
        name: ibm
        state: present
    - name: add user
      user:
        name: test
        state: present
    - name: add user
      user: 
        name: new
        state: present
